# Generated by Django 4.0 on 2021-12-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('fees', models.BooleanField()),
            ],
        ),
    ]
